---

version: '3.1'
services:
  web:
    image: odoo:13
    container_name: odoo_ui
    restart: always
    depends_on:
      - db
    ports:
      - "80:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2023
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo_network

  db:
    image: postgres:15
    container_name: odoo_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2023
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo_network

  pgadmin4:
      image: elestio/pgadmin:REL-8_5
      container_name: odoo_pgadmin
      restart: always
      depends_on:
        - db
      ports:
        - "85:8080"
      environment:
        PGADMIN_DEFAULT_EMAIL: rabinauget@gmail.com
        PGADMIN_DEFAULT_PASSWORD: pgadmin17@2023
        PGADMIN_LISTEN_PORT: 8080
      volumes:
        - ./servers.json:/pgadmin4/servers.json
        - ./pgpass:/pgpass
      networks:
      - odoo_network

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo_network:
